services:
  - type: web
    name: mini-blog-api
    env: node
<<<<<<< HEAD
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
=======
    buildCommand: npm install
    startCommand: npm start
>>>>>>> 77d6ea44d6f703885c2465524020da69b78fd06e
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
<<<<<<< HEAD
        value: 3000
=======
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: mini-blog-db
          property: connectionString

databases:
  - name: mini-blog-db
    databaseName: mini_blog
    user: mini_blog_user
    plan: free
>>>>>>> 77d6ea44d6f703885c2465524020da69b78fd06e
