services:
  - type: web
    name: mini-blog-api
    env: node
    buildCommand: npm install
    startCommand: npm run init-db && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        value: postgresql://blog_database_dlnf_user:b59vQMacaHWOskite8X8y2D3iarBdo9o@dpg-d4te90vgi27c73df5ve0-a/blog_database_dlnf